### ISSUE TITLE
Performance issues with mallocAssemblyScriptString

### ISSUE THREAD

**Issue by paulo** [DevCycleHQ/go-server-sdk#86]
I'm running some local benchmarks and hitting performance issues when doing simple boolean flag evals. Specifically, I'm seeing increased memory usage when executing `mallocAssemblyScriptString`.

Pprof:

<img width="723" alt="image" src="https://user-images.githubusercontent.com/4138302/222701417-b46ee181-c621-47fe-8eca-498f33db769d.png">

Benchmark code:
```
func BenchmarkDevCycle(b *testing.B) {
	dcKey := os.Getenv("DEVCYCLE_KEY")
	if dcKey == "" {
		b.Errorf("DEVCYCLE_KEY not set")
		return
	}

	devOpts := &devcycle.DVCOptions{
		EnableEdgeDB:                 false,
		EnableCloudBucketing:         false,
		RequestTimeout:               time.Second * 2,
		DisableAutomaticEventLogging: false,
		DisableCustomEventLogging:    true,
		EventFlushIntervalMS:         time.Second * 30,
		ConfigPollingIntervalMS:      time.Second * 10,
		FlushEventQueueSize:          5000,
		MaxEventQueueSize:            50000,
	}

	client, err := devcycle.NewDVCClient(dcKey, devOpts)
	require.NoError(b, err)

	user := devcycle.DVCUser{UserId: "dontcare"}

	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		_, err = client.Variable(user, flagBasicBool, false)
		require.NoError(b, err)
	}
}
```

Results from running the benchmark:

```
goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
BenchmarkDevCycle-8     2023/03/03 11:46:30
      22         252447202 ns/op        961463663 B/op    143211 allocs/op
PASS
ok      16.488s
```

Any idea why this might be happening? I see that due that because the lib is using `bytecodealliance/wasmtime-go` you have to do some low-level memory manipulation operations in order to parse the resulting payload the wasm runtime, so maybe something to look into first.

**Comment by JamieSinn** [comment]
The main reason is to force allocations and prevent garbage collection between parameter creation, but then to allow it once we've used the param. 

Are you able to let it sleep for a while after the bench loop? The internal Assembly script gc should trigger, though I'm not certain the time it's currently running inside the benchmark will cause a gc.


Definitely will be investigating!

**Comment by paulo** [comment]
> Are you able to let it sleep for a while after the bench loop? The internal Assembly script gc should trigger, though I'm not certain the time it's currently running inside the benchmark will cause a gc.

I understand that GC may not be running instantly and that can cause an increased memory usage, but what I'm more concerned about here is the `252447202 ns/op` performance that the benchmark is showing. I'd expect a single bool evaluation to be at the very worst no more than 10 milliseconds.

**Comment by jonathannorris** [comment]
@paulo apologize if my questions are a bit basic as I'm not as experienced with GO. Are you able to measure the speed of creating the `NewDVCClient()` outside of the benchmark? As I would expect the initialization step to be the slowest part of the process as it downloads the config from our CDN and loads your config into the WASM memory. We know that loading larger project configs into WASM can be slower and we are working on optimizing that.

However, we would expect the `Variable()` call to be fast once the SDK has been initialized (I believe we have some benchmark tests on this already). So you may need to wait for the `onInitializedChannel` before measuring the performance of the `Variable` call directly: https://docs.devcycle.com/docs/sdk/server-side-sdks/go#getting-started

**Comment by jonathannorris** [comment]
@paulo just ran [this benchmark](https://github.com/DevCycleHQ/go-server-sdk/blob/main/localbucketing_test.go#L128) we have which tests calling the local bucketing WASM code directly and got `264274 ns/op`. Will set up a test that calls `.Variable()` directly and test that way, also will check with a larger project config.

```
goos: darwin
goarch: arm64
pkg: github.com/devcyclehq/go-server-sdk/v2
BenchmarkDevCycleLocalBucketing_GenerateBucketedConfigForUser
2023/03/03 10:13:32 WARN: EventFlushIntervalMS cannot be less than 500ms or longer than 1 minute. Defaulting to 30 seconds.
2023/03/03 10:13:32 WARN: ConfigPollingIntervalMS cannot be less than 1 second. Defaulting to 10 seconds.
2023/03/03 10:13:32 WARN: EventFlushIntervalMS cannot be less than 500ms or longer than 1 minute. Defaulting to 30 seconds.
2023/03/03 10:13:32 WARN: ConfigPollingIntervalMS cannot be less than 1 second. Defaulting to 10 seconds.
2023/03/03 10:13:32 WARN: EventFlushIntervalMS cannot be less than 500ms or longer than 1 minute. Defaulting to 30 seconds.
2023/03/03 10:13:32 WARN: ConfigPollingIntervalMS cannot be less than 1 second. Defaulting to 10 seconds.
2023/03/03 10:13:33 WARN: EventFlushIntervalMS cannot be less than 500ms or longer than 1 minute. Defaulting to 30 seconds.
2023/03/03 10:13:33 WARN: ConfigPollingIntervalMS cannot be less than 1 second. Defaulting to 10 seconds.
BenchmarkDevCycleLocalBucketing_GenerateBucketedConfigForUser-10    	    4512	    264274 ns/op
PASS
```

**Comment by paulo** [comment]
> Are you able to measure the speed of creating the NewDVCClient() outside of the benchmark? As I would expect the initialization step to be the slowest part of the process as it downloads the config from our CDN and loads your config into the WASM memory. We know that loading larger project configs into WASM can be slower and we are working on optimising that.

Great point! I've updated the benchmark to the following, which doesn't take into account the setup part and waits for the client to init:

```
func BenchmarkDevCycle(b *testing.B) {
	dcKey := os.Getenv("DEVCYCLE_KEY")
	if dcKey == "" {
		b.Errorf("DEVCYCLE_KEY not set")
		return
	}

	onInitializedChannel := make(chan bool) // optional

	devOpts := &devcycle.DVCOptions{
		EnableEdgeDB:                 false,
		EnableCloudBucketing:         false,
		RequestTimeout:               time.Second * 2,
		DisableAutomaticEventLogging: false,
		DisableCustomEventLogging:    true,
		EventFlushIntervalMS:         time.Second * 30,
		ConfigPollingIntervalMS:      time.Second * 10,
		FlushEventQueueSize:          0,
		MaxEventQueueSize:            0,
		OnInitializedChannel:         onInitializedChannel,
	}

	client, err := devcycle.NewDVCClient(dcKey, devOpts)
	require.NoError(b, err)

	<-onInitializedChannel

	user := devcycle.DVCUser{UserId: "dontcare"}

	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		_, err = client.Variable(user, flagBasicBool, false)
		require.NoError(b, err)
	}
}
```

However, I'm still getting somewhat poor performance, and as you can see, the `OnInitializedChannel` block is apparently getting sent to too soon?

```
goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
BenchmarkDevCycle-8     
2023/03/03 16:16:09 WARN: Variable called before client initialized, returning default value
2023/03/03 16:16:09 WARN: Variable called before client initialized, returning default value
2023/03/03 16:16:09 WARN: Variable called before client initialized, returning default value
2023/03/03 16:16:09 WARN: Variable called before client initialized, returning default value
...
     100         182256801 ns/op        721032076 B/op    101402 allocs/op
PASS
ok    18.880s
```

**Comment by paulo** [comment]
> @paulo just ran [this benchmark](https://github.com/DevCycleHQ/go-server-sdk/blob/main/localbucketing_test.go#L128) we have which tests calling the local bucketing WASM code directly and got 264274 ns/op. Will set up a test that calls .Variable() directly and test that way, also will check with a larger project config.

I notice you're using arm64, can you perhaps try it out on amd64? (I realise you might not have 2 computers running different archs at hand 😂)

**Comment by JamieSinn** [comment]
With the recent changes to use `-tags native_bucketing` - and given our current benchmarks are in the 100's of ns range for variable eval - I think we're safe to close this

- https://github.com/DevCycleHQ/go-server-sdk/actions/runs/4855269335/jobs/8653641255#step:4:27
